insert into classes values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JAVA', 'NIX9', 'Alex Morgan');
insert into classes values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'PYTHON', 'NIX8', 'Trevor Malone');
insert into classes values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JS', 'NIX10', 'Andrew Morgan');
insert into classes values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JAVA', 'NIX6', 'Andy Bunting');
insert into classes values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'KOTLIN', 'NIX5', 'Jason Lowe');
insert into classes values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'KOTLIN', 'NIX9', 'Jason Lowe');
insert into classes values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JAVA', 'NIX4', 'Alex Morgan');
insert into classes values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JAVA', 'NIX3', 'Andy Bunting');
insert into classes values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JS', 'EPAM2', 'Jimmy Petersen');
insert into classes values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'QA', 'ALEVEL1', 'Lisa Ashton');
insert into classes values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JAVA', 'NIX2', 'Alex Morgan');
insert into classes values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JAVA', 'EPAM1', 'Andy Bunting');
insert into classes values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'JS', 'ALEVEL2', 'Jimmy Petersen');
insert into classes values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'PYTHON', 'EPAM3', 'Victor Hempel');

insert into students values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 19, 'ritchie.edhouse@gmail.com', 'Ritchie', 'Edhouse','0991234324');
insert into students values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 22, 'lihao.wen@gmail.com', 'Lihao', 'Wen', '0508756257');
insert into students values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 24, 'ricky.evans@gmail.com', 'Ricky', 'Evans', '09758901234');
insert into students values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 21, 'adrian.lewis@gmail.com', 'Adrian', 'Lewis', '0660012398');
insert into students values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 18, 'matt.campbell@gmail.com', 'Matt', 'Campbell', '09987024612');
insert into students values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 23, 'gerwyn.price@gmail.com', 'Gerwyn', 'Price', '05798241287');
insert into students values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 18, 'steve.lennon@gmail.com', 'Steve', 'Lennon', '09992461449');
insert into students values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 17, 'scott.mitchell@gmail.com', 'Scott', 'Mitchell', '0677927589');
insert into students values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 23, 'madars.razma@gmail.com', 'Madars', 'Razma', '0669314300');
insert into students values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 19, 'chris.landman@gmail.com', 'Chris', 'Landman', '0993894640');
insert into students values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 21, 'chas.barstow@gmail.com', 'Chas', 'Barstow', '0975648130');
insert into students values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 18, 'daryl.gurney@gmail.com', 'Daryl', 'Gurney', '0979246706');
insert into students values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 22, 'gary.anderson@gmail.com', 'Gary', 'Anderson', '0916779440');
insert into students values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 22, 'ryan.meikle@gmail.com', 'Ryan', 'Meikle' , '0988249573');
insert into students values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 28, 'keane.barry@gmail.com', 'Keane', 'Barry', '0637355919');
insert into students values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 31, 'jonny.clayton@gmail.com', 'Jonny', 'Clayton', '0968522158');
insert into students values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 16, 'jeff.smith@gmail.com', 'Jeff', 'Smith', '0677695917');
insert into students values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 20, 'michael.smith@gmail.com', 'Michael', 'Smith', '0664105537');

insert into study_records values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,1);
insert into study_records values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,7);
insert into study_records values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,8);
insert into study_records values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,4);
insert into study_records values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,12);
insert into study_records values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,2);
insert into study_records values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,9);
insert into study_records values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,3);
insert into study_records values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,6);
insert into study_records values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,15);
insert into study_records values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,17);
insert into study_records values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,18);
insert into study_records values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,1);
insert into study_records values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,2);
insert into study_records values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,3);
insert into study_records values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,10);
insert into study_records values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,12);
insert into study_records values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,11);
insert into study_records values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,9);
insert into study_records values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,4);
insert into study_records values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,5);
insert into study_records values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,4);
insert into study_records values (23, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,3);
insert into study_records values (24, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,16);
insert into study_records values (25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,13);
insert into study_records values (26, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,14);
insert into study_records values (27, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,1);
insert into study_records values (28, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,18);
