insert into classes values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX9', 'Alex Morgan', 'JAVA');
insert into classes values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX8', 'Trevor Malone', 'PYTHON');
insert into classes values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX10', 'Andrew Morgan', 'JS');
insert into classes values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX6', 'Andy Bunting', 'JAVA');
insert into classes values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX5', 'Jason Lowe', 'KOTLIN');
insert into classes values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX9', 'Jason Lowe', 'KOTLIN');
insert into classes values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX4', 'Alex Morgan', 'JAVA');
insert into classes values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX3', 'Andy Bunting', 'JAVA');
insert into classes values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'EPAM2', 'Jimmy Petersen', 'JS');
insert into classes values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ALEVEL1', 'Lisa Ashton', 'QA');
insert into classes values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'NIX2', 'Alex Morgan', 'JAVA');
insert into classes values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'EPAM1', 'Andy Bunting', 'JAVA');
insert into classes values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'ALEVEL2', 'Jimmy Petersen', 'JS');
insert into classes values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'EPAM3', 'Victor Hempel', 'PYTHON');

insert into students values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Ritchie', 'Edhouse', 19, '0991234324', 'ritchie.edhouse@gmail.com');
insert into students values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Lihao', 'Wen', 22, '0508756257', 'lihao.wen@gmail.com');
insert into students values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Ricky', 'Evans', 24, '09758901234', 'ricky.evans@gmail.com');
insert into students values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Adrian', 'Lewis', 21, '0660012398', 'adrian.lewis@gmail.com');
insert into students values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Matt', 'Campbell', 18, '09987024612', 'matt.campbell@gmail.com');
insert into students values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gerwyn', 'Price', 23, '05798241287', 'gerwyn.price@gmail.com');
insert into students values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Steve', 'Lennon', 18, '09992461449', 'steve.lennon@gmail.com');
insert into students values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Scott', 'Mitchell', 17, '0677927589', 'scott.mitchell@gmail.com');
insert into students values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Madars', 'Razma', 23, '0669314300', 'madars.razma@gmail.com');
insert into students values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Chris', 'Landman', 19, '0993894640', 'chris.landman@gmail.com');
insert into students values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Chas', 'Barstow', 21, '0975648130', 'chas.barstow@gmail.com');
insert into students values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Daryl', 'Gurney', 18, '0979246706', 'daryl.gurney@gmail.com');
insert into students values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Gary', 'Anderson', 22, '0916779440', 'gary.anderson@gmail.com');
insert into students values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Ryan', 'Meikle', 22, '0988249573', 'ryan.meikle@gmail.com');
insert into students values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Keane', 'Barry', 28, '0637355919', 'keane.barry@gmail.com');
insert into students values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Jonny', 'Clayton', 31, '0968522158', 'jonny.clayton@gmail.com');
insert into students values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Jeff', 'Smith', 16, '0677695917', 'jeff.smith@gmail.com');
insert into students values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 'Michael', 'Smith', 20, '0664105537', 'michael.smith@gmail.com');

insert into record values (1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,1);
insert into record values (2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,7);
insert into record values (3, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,8);
insert into record values (4, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,4);
insert into record values (5, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,12);
insert into record values (6, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,2);
insert into record values (7, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 1,9);
insert into record values (8, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,3);
insert into record values (9, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,6);
insert into record values (10, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,15);
insert into record values (11, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,17);
insert into record values (12, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 2,18);
insert into record values (13, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,1);
insert into record values (14, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,2);
insert into record values (15, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,3);
insert into record values (16, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,10);
insert into record values (17, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,12);
insert into record values (18, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,11);
insert into record values (19, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,9);
insert into record values (20, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 3,4);
insert into record values (21, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,5);
insert into record values (22, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,4);
insert into record values (23, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,3);
insert into record values (24, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,16);
insert into record values (25, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,13);
insert into record values (26, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,14);
insert into record values (27, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,1);
insert into record values (28, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP(), 10,18);
